version: '3'

services:
  project-service:
    image: docker.nexus.archi-lab.io/archilab/prox-project-service
    ports:
      - "9002:9002"
    restart: always
    networks:
      - ptb
      - project-db

  project-db:
    image: postgres:11.2-alpine
    volumes:
      - project-db-data:/var/lib/postgresql/data
    restart: always
    environment:
      - POSTGRES_USER=project-service
      - POSTGRES_PASSWORD=project-service
      - POSTGRES_DB=project-db
      - PGDATA=/var/lib/postgresql/data/pgdata
    networks:
      - project-db

volumes:
  project-db-data:

networks:
  ptb:
    external: true
  project-db:
