create table module (id uuid not null, self_ref varchar(255), name varchar(255), primary key (id));
create table project (id uuid not null, created timestamp, creatorid uuid, creator_name varchar(255), description varchar(3000), modified timestamp, name varchar(255), status int4, supervisor_name varchar(255), primary key (id));
create table project_modules (project_id uuid not null, modules_id uuid not null);
create table study_course (id uuid not null, academic_degree int4, self_ref varchar(255), name varchar(255), primary key (id));
create table study_course_modules (study_course_id uuid not null, modules_id uuid not null);
alter table study_course_modules add constraint UK_rc2bmnapbpjlhf4njn4pt26w5 unique (modules_id);
alter table project_modules add constraint FKocfqox59i6wienpi4edogg3e5 foreign key (modules_id) references module;
alter table project_modules add constraint FKgo9qewo8ghgvhjf5klastib5r foreign key (project_id) references project;
alter table study_course_modules add constraint FKskyjks4jio6loxb65i5lers58 foreign key (modules_id) references module;
alter table study_course_modules add constraint FKk4jslg7rbwc4be8ggf1mw3ei2 foreign key (study_course_id) references study_course;
